services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  logic-app:
    build: ./logic
    container_name: logic-app
    depends_on:
      - ollama
    ports:
      - "8501:8501"
    restart: always

volumes:
  ollama_data:
