services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    # See rida garanteerib, et kõik vajalikud mudelid tõmmatakse automaatselt käivitamisel
    entrypoint: /bin/sh -c "ollama serve & sleep 10 && ollama pull llama3:8b && ollama pull gemma2:2b && ollama pull mistral && ollama pull phi3 && ollama pull mxbai-embed-large && ollama pull bge-m3 && wait"

  api:
    build: ./api
    container_name: api-service
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

  logic-app:
    build: ./logic
    container_name: logic-app
    working_dir: /app
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    # Käivitame Streamlit rakenduse
    command: >
      streamlit run main.py 
      --server.address=0.0.0.0 
      --server.port=8501 
      --server.enableCORS=false 
      --server.enableXsrfProtection=false 
      --server.headless=true
    depends_on:
      - ollama
    ports:
      - "8501:8501"
    volumes:
      - ./logic:/app
      - ./storage/vector_db:/app/chroma_db
      - ./data_pipeline:/app/data_pipeline
      - ./storage:/app/storage

  test-app:
    build: ./logic
    container_name: test-app
    working_dir: /app
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    # See konteiner ootab käsku (manual trigger) või käivitab konkreetse testi
    command: tail -f /dev/null
    depends_on:
      - ollama
    volumes:
      - ./logic:/app
      - ./data_pipeline:/app/data_pipeline
      - ./storage:/app/storage

volumes:
  ollama_data: